// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfD4r6IFi83YRjxkhdjggPvD0_AVjgY0c',
    appId: '1:104225980114:web:2c7719918eb2d0fb9af70b',
    messagingSenderId: '104225980114',
    projectId: 'joola-2d252',
    authDomain: 'joola-2d252.firebaseapp.com',
    storageBucket: 'joola-2d252.appspot.com',
    measurementId: 'G-HP59SJBG11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWTqIKU53o1biXsjMy4_GjDVlR7tcTGEw',
    appId: '1:104225980114:android:957d4a2e700e9fa39af70b',
    messagingSenderId: '104225980114',
    projectId: 'joola-2d252',
    storageBucket: 'joola-2d252.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8x-E-XPh6fZOMO9qBSa34pB3BGFKZrOQ',
    appId: '1:104225980114:ios:748bbd803dd64c269af70b',
    messagingSenderId: '104225980114',
    projectId: 'joola-2d252',
    storageBucket: 'joola-2d252.appspot.com',
    iosClientId: '104225980114-m4oelnilj5davblaahkikt351m4i03p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.joola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8x-E-XPh6fZOMO9qBSa34pB3BGFKZrOQ',
    appId: '1:104225980114:ios:748bbd803dd64c269af70b',
    messagingSenderId: '104225980114',
    projectId: 'joola-2d252',
    storageBucket: 'joola-2d252.appspot.com',
    iosClientId: '104225980114-m4oelnilj5davblaahkikt351m4i03p5.apps.googleusercontent.com',
    iosBundleId: 'com.example.joola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfD4r6IFi83YRjxkhdjggPvD0_AVjgY0c',
    appId: '1:104225980114:web:893baa92ca5b75f99af70b',
    messagingSenderId: '104225980114',
    projectId: 'joola-2d252',
    authDomain: 'joola-2d252.firebaseapp.com',
    storageBucket: 'joola-2d252.appspot.com',
    measurementId: 'G-4ZK6CKER7H',
  );
}
